### ISSUE TITLE
[1.7.10] - Crash on modpack launch with latest version

### ISSUE THREAD

**Issue by syndicate25** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#63]
Crashing on load with my custom modpack, Progressive Survival.  I'm in progress of updating all the mods and as soon as I updated this one, it won't load anymore.  Attached below is a screenshot of the modlist along with a pastebin to the crash report.  Crashing on step 2/7 during loading.

Edit: A little testing and it looks like the latest version that works for me is Chunk Pregenerator-V1.7.10-2.5.3.  Anything after that crashes, though it's at different phases of loading for each one.

![modlist](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/22588398/a54efd4b-0f4a-43b6-ad6d-2a3dfb3f6420)

See full crash report here:

https://pastebin.com/j0hhjqSm

**Comment by Speiger** [comment]
I implemented a fancy icon system for ChunkPregens preview.

False tweaks doesn't like that I use vanillas atlas builder.

Simply change:
"TEXTURE_OPTIMIZATIONS"
In the configs to false and that will fix it.

**Comment by syndicate25** [comment]
Thank you.  I'll give that a shot here in a second and update this shortly!

**Comment by Speiger** [comment]
@syndicate25 its actually a 100% fix. Let me update the issue tracker to contain it.

**Comment by Speiger** [comment]
Closing. Updated known issues entry to include false tweaks and why it happens and the manual fix within it.

**Comment by syndicate25** [comment]
@Speiger Let me know if you want a new issue for this, but it's failing on step 5/7 now.

https://pastebin.com/10CW3Zzm

**Comment by Speiger** [comment]
@syndicate25 i checked the log and its the exact same issue because the config wasn't set to false

**Comment by syndicate25** [comment]
I changed the value to false in falsetweaks.cfg.  Is there another config I have to change?
[falsetweaks.txt](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/15302605/falsetweaks.txt)

**Comment by Speiger** [comment]
@syndicate25 then you need to disable falsetweaks during pregen and then once finished swap them back in.
Luckily that isn't a huge problem ^^"

Outside of writing my own texture stitcher (which i kinda don't want to do) there is nothing i can do...
And any other mod that uses a stitcher will break that one too.

**Comment by syndicate25** [comment]
Okay.. And how do I do what you're suggesting?

**Comment by Speiger** [comment]
@syndicate25 
- temporarly uninstall falsetweaks (simply add a .disable as file extension after .jar).
- Run chunkpregenerator
- Once done uninstall chunkpregen
- install false tweaks.

**Comment by syndicate25** [comment]
I see. So if I want this in my modpack, it sounds like I'd have to stick with version 2.5.3 since I don't think it's reasonable to assume everyone who downloads the pack is going to understand how to do that or why they have to.. 

It looks like a workaround for a specific world?

**Comment by Speiger** [comment]
yeah maybe, though any bugs found there can't be validated there anymore since i fixed a ton of them in the mega patch.

yeah.

**Comment by Speiger** [comment]
@syndicate25 according to the false tweaks dev in version "3.0.0 Beta 4" it should be fixed.
Would you try it please?

**Comment by syndicate25** [comment]
I tried this today, with CPG 4.4.5 and FT 3.0.0-beta0004.  I am still experiencing crashes with "TEXTURE_OPTIMIZATIONS" set to either true or false.  It will crash at different loading phases depending on what value is saved in the config.

Here's a report for the latest crash with TO set to "false."

https://pastebin.com/WVmYZr9m

**Comment by Speiger** [comment]
@FalsePattern Looks like this is still an issue (moving it here for ease of tracking)

**Comment by FalsePattern** [comment]
That piece of code never loads with TEXTURE_OPTIMIZATIONS set to false. Please delete `falsetweaks.cfg`, you might be trying to change a deprecated config option that got persisted by Forge's config engine.

**Comment by FalsePattern** [comment]
Delete the AnimFix jar, it's been merged into FalseTweaks (it's also mentioned in the readme, but it's easy to miss i guess...). After that, re-enable TEXTURE_OPTIMIZATIONS.

**Comment by Speiger** [comment]
@FalsePattern thank you for your help!
@syndicate25 ping

Once confirmed I will update the known issues section

**Comment by syndicate25** [comment]
> Delete the AnimFix jar, it's been merged into FalseTweaks (it's also mentioned in the readme, but it's easy to miss i guess...). After that, re-enable TEXTURE_OPTIMIZATIONS.

I've been out of the MC game for a bit and have recently decided to start updating my pack.  I was keeping up on this stuff for a while, but I'm sure there's more I've missed since and appreciate your help as well as @Speiger on this. 

I removed animfix and reset the TEXTURE_OPTIMIZATIONS back to "true."

I'm happy to report that resolved my problem and I can load the pack now.

Thanks again guys!
